-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgky7GBSpnpcAnhjKM
zUI2885tbd7/U/Aftd5HCdz+jgmgCgYIKoZIzj0DAQehRANCAATEv0rwhnLkndxM
ROdT/mMjFvBiQ9dVekl3dYZvbLlF9CB2QsDVVWV9aeeNBUYZneJfZlJPKOgeRdV7
SKo8g/Mo
-----END PRIVATE KEY-----